-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_user_id uuid,
  organization_id uuid,
  admin_member_id uuid,
  action text NOT NULL,
  action_category text DEFAULT 'general'::text,
  action_severity text DEFAULT 'info'::text,
  resource_type text,
  resource_id uuid,
  resource_name text,
  before_snapshot jsonb,
  after_snapshot jsonb,
  changed_fields ARRAY,
  change_summary text,
  request_id text,
  session_id uuid,
  ip_address inet,
  user_agent text,
  country_code character,
  region text,
  city text,
  authentication_method text,
  authentication_provider text,
  processing_time_ms integer CHECK (processing_time_ms >= 0),
  status text DEFAULT 'success'::text,
  error_message text,
  error_stack text,
  retention_period_days integer DEFAULT 365,
  is_sensitive boolean DEFAULT false,
  is_archived boolean DEFAULT false,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT admin_audit_logs_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES public.profiles(id),
  CONSTRAINT admin_audit_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT admin_audit_logs_admin_member_id_fkey FOREIGN KEY (admin_member_id) REFERENCES public.organization_members(id),
  CONSTRAINT admin_audit_logs_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.user_sessions(id)
);
CREATE TABLE public.analytics_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  actor_id uuid,
  organization_id uuid,
  actor_member_id uuid,
  event_type text NOT NULL,
  event_category text DEFAULT 'general'::text,
  event_source text DEFAULT 'web'::text,
  session_id uuid,
  request_id text,
  trace_id text,
  ip_address inet,
  user_agent text,
  device_type text,
  browser_family text,
  browser_version text,
  os_family text,
  os_version text,
  country_code character,
  region text,
  city text,
  timezone text,
  page_url text,
  page_title text,
  page_referrer text,
  page_path text,
  utm_parameters jsonb DEFAULT '{}'::jsonb,
  event_props jsonb DEFAULT '{}'::jsonb,
  event_metrics jsonb DEFAULT '{}'::jsonb,
  load_time_ms integer CHECK (load_time_ms >= 0),
  processing_time_ms integer CHECK (processing_time_ms >= 0),
  is_processed boolean DEFAULT false,
  processed_at timestamp with time zone,
  is_valid boolean DEFAULT true,
  validation_errors ARRAY,
  is_anonymized boolean DEFAULT false,
  data_retention_days integer DEFAULT 365,
  gdpr_compliant boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analytics_events_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_events_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(id),
  CONSTRAINT analytics_events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT analytics_events_actor_member_id_fkey FOREIGN KEY (actor_member_id) REFERENCES public.organization_members(id),
  CONSTRAINT analytics_events_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.user_sessions(id)
);
CREATE TABLE public.analytics_funnels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  created_by_member_id uuid,
  name text NOT NULL,
  description text,
  steps jsonb NOT NULL,
  is_active boolean DEFAULT true,
  conversion_window_days integer DEFAULT 30 CHECK (conversion_window_days > 0),
  require_sequence boolean DEFAULT true,
  audience_filters jsonb DEFAULT '{}'::jsonb,
  total_conversions integer DEFAULT 0 CHECK (total_conversions >= 0),
  conversion_rate numeric CHECK (conversion_rate >= 0::numeric AND conversion_rate <= 100::numeric),
  average_conversion_time_days numeric CHECK (average_conversion_time_days >= 0::numeric),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analytics_funnels_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_funnels_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT analytics_funnels_created_by_member_id_fkey FOREIGN KEY (created_by_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.analytics_metric_values (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  metric_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  period_start timestamp with time zone NOT NULL,
  period_end timestamp with time zone NOT NULL,
  metric_value numeric NOT NULL,
  dimension_filters jsonb DEFAULT '{}'::jsonb,
  previous_value numeric,
  value_change numeric,
  percent_change numeric,
  confidence_interval jsonb,
  data_quality_score numeric CHECK (data_quality_score >= 0::numeric AND data_quality_score <= 100::numeric),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analytics_metric_values_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_metric_values_metric_id_fkey FOREIGN KEY (metric_id) REFERENCES public.analytics_metrics(id),
  CONSTRAINT analytics_metric_values_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.analytics_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  metric_name text NOT NULL,
  metric_type text NOT NULL,
  metric_category text DEFAULT 'general'::text,
  description text,
  calculation_query text,
  aggregation_period text DEFAULT 'daily'::text,
  dimensions ARRAY DEFAULT '{}'::text[],
  target_value numeric,
  target_direction text,
  is_business_critical boolean DEFAULT false,
  is_active boolean DEFAULT true,
  last_calculated_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analytics_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_metrics_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.analytics_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  organization_id uuid,
  user_member_id uuid,
  session_token text NOT NULL UNIQUE,
  device_id text,
  session_started_at timestamp with time zone NOT NULL DEFAULT now(),
  session_ended_at timestamp with time zone,
  last_activity_at timestamp with time zone DEFAULT now(),
  session_props jsonb DEFAULT '{"exit_page": "/", "entry_page": "/", "is_first_visit": true, "is_returning_user": false}'::jsonb,
  user_agent text,
  ip_address inet,
  screen_resolution text,
  viewport_size text,
  language_code text DEFAULT 'en'::text,
  page_views integer DEFAULT 1 CHECK (page_views >= 0),
  events_count integer DEFAULT 1 CHECK (events_count >= 0),
  session_duration_seconds integer CHECK (session_duration_seconds >= 0),
  country_code character,
  region text,
  city text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analytics_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT analytics_sessions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT analytics_sessions_user_member_id_fkey FOREIGN KEY (user_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.asset_access_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_id uuid NOT NULL,
  accessed_by_profile_id uuid,
  organization_id uuid,
  accessed_by_member_id uuid,
  access_type text NOT NULL,
  access_method text DEFAULT 'direct'::text,
  ip_address inet,
  user_agent text,
  country_code character,
  shared_link_id uuid,
  access_token text,
  load_time_ms integer CHECK (load_time_ms >= 0),
  bytes_transferred bigint CHECK (bytes_transferred >= 0),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT asset_access_logs_pkey PRIMARY KEY (id),
  CONSTRAINT asset_access_logs_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id),
  CONSTRAINT asset_access_logs_accessed_by_profile_id_fkey FOREIGN KEY (accessed_by_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT asset_access_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT asset_access_logs_accessed_by_member_id_fkey FOREIGN KEY (accessed_by_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.asset_collection_memberships (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_id uuid NOT NULL,
  collection_id uuid NOT NULL,
  organization_id uuid,
  added_by_member_id uuid,
  display_order integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT asset_collection_memberships_pkey PRIMARY KEY (id),
  CONSTRAINT asset_collection_memberships_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id),
  CONSTRAINT asset_collection_memberships_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES public.asset_collections(id),
  CONSTRAINT asset_collection_memberships_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT asset_collection_memberships_added_by_member_id_fkey FOREIGN KEY (added_by_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.asset_collections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  created_by_member_id uuid,
  name text NOT NULL,
  description text,
  slug text NOT NULL,
  is_public boolean DEFAULT false,
  visibility text DEFAULT 'private'::text,
  allow_uploads boolean DEFAULT true,
  require_approval boolean DEFAULT false,
  department text,
  project_name text,
  collection_type text DEFAULT 'general'::text,
  max_assets integer CHECK (max_assets >= 0),
  max_file_size_bytes bigint CHECK (max_file_size_bytes >= 0),
  allowed_mime_types ARRAY DEFAULT '{}'::text[],
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT asset_collections_pkey PRIMARY KEY (id),
  CONSTRAINT asset_collections_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT asset_collections_created_by_member_id_fkey FOREIGN KEY (created_by_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.asset_shared_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_id uuid NOT NULL,
  created_by_member_id uuid,
  organization_id uuid,
  share_token text NOT NULL UNIQUE,
  share_url text NOT NULL,
  is_active boolean DEFAULT true,
  access_level text DEFAULT 'view'::text,
  password_hash text,
  max_uses integer CHECK (max_uses >= 0),
  use_count integer DEFAULT 0 CHECK (use_count >= 0),
  expires_at timestamp with time zone,
  last_used_at timestamp with time zone,
  require_email boolean DEFAULT false,
  allowed_emails ARRAY DEFAULT '{}'::text[],
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT asset_shared_links_pkey PRIMARY KEY (id),
  CONSTRAINT asset_shared_links_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id),
  CONSTRAINT asset_shared_links_created_by_member_id_fkey FOREIGN KEY (created_by_member_id) REFERENCES public.organization_members(id),
  CONSTRAINT asset_shared_links_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  organization_id uuid,
  profile_member_id uuid,
  uploaded_by_member_id uuid,
  file_name text NOT NULL,
  file_path text NOT NULL,
  file_size_bytes bigint NOT NULL CHECK (file_size_bytes >= 0),
  mime_type text,
  bucket_name text NOT NULL,
  storage_provider text DEFAULT 'supabase'::text,
  storage_region text,
  storage_tier text DEFAULT 'standard'::text,
  file_extension text,
  dimensions jsonb,
  duration_ms integer CHECK (duration_ms >= 0),
  checksum_sha256 text,
  compression_ratio numeric CHECK (compression_ratio >= 0::numeric),
  is_public boolean DEFAULT false,
  visibility text DEFAULT 'private'::text,
  access_level text DEFAULT 'view'::text,
  password_hash text,
  expires_at timestamp with time zone,
  version_number integer DEFAULT 1 CHECK (version_number >= 1),
  parent_asset_id uuid,
  is_latest_version boolean DEFAULT true,
  download_count integer DEFAULT 0 CHECK (download_count >= 0),
  view_count integer DEFAULT 0 CHECK (view_count >= 0),
  last_accessed_at timestamp with time zone,
  last_downloaded_at timestamp with time zone,
  processing_status text DEFAULT 'pending'::text,
  processing_errors ARRAY,
  processed_at timestamp with time zone,
  optimizations jsonb DEFAULT '{}'::jsonb,
  variants jsonb DEFAULT '[]'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT assets_pkey PRIMARY KEY (id),
  CONSTRAINT assets_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT assets_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT assets_profile_member_id_fkey FOREIGN KEY (profile_member_id) REFERENCES public.organization_members(id),
  CONSTRAINT assets_uploaded_by_member_id_fkey FOREIGN KEY (uploaded_by_member_id) REFERENCES public.organization_members(id),
  CONSTRAINT assets_parent_asset_id_fkey FOREIGN KEY (parent_asset_id) REFERENCES public.assets(id)
);
CREATE TABLE public.audit_log_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  triggered_by_member_id uuid,
  alert_type text NOT NULL,
  alert_severity text DEFAULT 'medium'::text,
  title text NOT NULL,
  description text,
  trigger_conditions jsonb DEFAULT '{}'::jsonb,
  matched_logs jsonb DEFAULT '[]'::jsonb,
  status text DEFAULT 'active'::text,
  acknowledged_at timestamp with time zone,
  acknowledged_by uuid,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  notification_sent boolean DEFAULT false,
  notification_sent_at timestamp with time zone,
  notification_methods ARRAY DEFAULT '{in_app}'::text[],
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_log_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_alerts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT audit_log_alerts_triggered_by_member_id_fkey FOREIGN KEY (triggered_by_member_id) REFERENCES public.organization_members(id),
  CONSTRAINT audit_log_alerts_acknowledged_by_fkey FOREIGN KEY (acknowledged_by) REFERENCES public.profiles(id),
  CONSTRAINT audit_log_alerts_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.audit_log_configurations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  created_by_member_id uuid,
  name text NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  rules jsonb DEFAULT '{"minimum_severity": "low", "enabled_categories": ["user_management", "security", "system"], "log_failed_actions": true, "log_read_operations": false, "log_successful_actions": true, "log_sensitive_operations": true}'::jsonb,
  retention_policies jsonb DEFAULT '{"general_logs": 365, "security_logs": 1825, "sensitive_logs": 730, "compliance_logs": 2555}'::jsonb,
  alert_rules jsonb DEFAULT '{"unusual_activity": true, "sensitive_operations": true, "high_severity_actions": true, "failed_logins_threshold": 5}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_log_configurations_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_configurations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT audit_log_configurations_created_by_member_id_fkey FOREIGN KEY (created_by_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.audit_log_exports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  requested_by_member_id uuid,
  export_type text NOT NULL,
  format text DEFAULT 'json'::text,
  status text DEFAULT 'pending'::text,
  date_range jsonb DEFAULT '{}'::jsonb,
  filters jsonb DEFAULT '{}'::jsonb,
  file_url text,
  file_size_bytes bigint,
  file_checksum text,
  download_count integer DEFAULT 0 CHECK (download_count >= 0),
  access_token text UNIQUE,
  is_encrypted boolean DEFAULT true,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '7 days'::interval),
  total_records integer DEFAULT 0 CHECK (total_records >= 0),
  processed_records integer DEFAULT 0 CHECK (processed_records >= 0),
  processing_started_at timestamp with time zone,
  processing_completed_at timestamp with time zone,
  error_message text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_log_exports_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_exports_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT audit_log_exports_requested_by_member_id_fkey FOREIGN KEY (requested_by_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.connection_recommendations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  recommended_user_id uuid NOT NULL,
  organization_id uuid,
  user_member_id uuid,
  recommended_member_id uuid,
  recommendation_source text NOT NULL,
  recommendation_reason text,
  confidence_score numeric CHECK (confidence_score >= 0::numeric AND confidence_score <= 1::numeric),
  shared_connections_count integer DEFAULT 0,
  shared_interests_count integer DEFAULT 0,
  shared_groups_count integer DEFAULT 0,
  shared_organizations_count integer DEFAULT 0,
  geographic_proximity numeric,
  shown_at timestamp with time zone,
  clicked_at timestamp with time zone,
  ignored_at timestamp with time zone,
  connected_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT connection_recommendations_pkey PRIMARY KEY (id),
  CONSTRAINT connection_recommendations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT connection_recommendations_recommended_user_id_fkey FOREIGN KEY (recommended_user_id) REFERENCES public.profiles(id),
  CONSTRAINT connection_recommendations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT connection_recommendations_user_member_id_fkey FOREIGN KEY (user_member_id) REFERENCES public.organization_members(id),
  CONSTRAINT connection_recommendations_recommended_member_id_fkey FOREIGN KEY (recommended_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.conversation_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  participant_id uuid NOT NULL,
  organization_id uuid,
  participant_member_id uuid,
  role text DEFAULT 'member'::text,
  joined_at timestamp with time zone DEFAULT now(),
  left_at timestamp with time zone,
  is_active boolean DEFAULT true,
  settings jsonb DEFAULT '{"muted": false, "archived": false, "notifications": true}'::jsonb,
  last_read_at timestamp with time zone,
  last_read_message_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conversation_participants_pkey PRIMARY KEY (id),
  CONSTRAINT conversation_participants_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT conversation_participants_participant_id_fkey FOREIGN KEY (participant_id) REFERENCES public.profiles(id),
  CONSTRAINT conversation_participants_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT conversation_participants_participant_member_id_fkey FOREIGN KEY (participant_member_id) REFERENCES public.organization_members(id),
  CONSTRAINT conversation_participants_last_read_message_id_fkey FOREIGN KEY (last_read_message_id) REFERENCES public.messages(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  organization_id uuid,
  created_by_member_id uuid,
  subject text,
  type text DEFAULT 'direct'::text,
  title text,
  description text,
  avatar_url text,
  is_public boolean DEFAULT false,
  is_archived boolean DEFAULT false,
  settings jsonb DEFAULT '{"moderated": false, "allow_replies": true, "read_receipts": true, "allow_attachments": true}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_message_at timestamp with time zone,
  last_message_id uuid,
  last_message_preview text,
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT conversations_created_by_member_id_fkey FOREIGN KEY (created_by_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.donation_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  created_by_member_id uuid,
  title text NOT NULL,
  description text,
  short_description text,
  goal_amount numeric CHECK (goal_amount >= 0::numeric),
  current_amount numeric DEFAULT 0 CHECK (current_amount >= 0::numeric),
  donor_count integer DEFAULT 0 CHECK (donor_count >= 0),
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  is_active boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  banner_url text,
  video_url text,
  images jsonb DEFAULT '[]'::jsonb,
  allow_recurring boolean DEFAULT true,
  allow_anonymous boolean DEFAULT true,
  allow_comments boolean DEFAULT true,
  minimum_amount numeric DEFAULT 1 CHECK (minimum_amount >= 0::numeric),
  campaign_type text DEFAULT 'general'::text,
  categories ARRAY DEFAULT '{}'::text[],
  tags ARRAY DEFAULT '{}'::text[],
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT donation_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT donation_campaigns_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT donation_campaigns_created_by_member_id_fkey FOREIGN KEY (created_by_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.donation_receipts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  donation_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  receipt_number text NOT NULL UNIQUE,
  receipt_date date NOT NULL,
  fiscal_year integer NOT NULL,
  donor_name text NOT NULL,
  donor_address jsonb,
  donor_email text,
  donor_phone text,
  amount numeric NOT NULL,
  currency character DEFAULT 'USD'::bpchar,
  is_tax_deductible boolean DEFAULT false,
  tax_deductible_amount numeric,
  status text DEFAULT 'draft'::text,
  sent_at timestamp with time zone,
  sent_via text,
  delivery_failure_reason text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT donation_receipts_pkey PRIMARY KEY (id),
  CONSTRAINT donation_receipts_donation_id_fkey FOREIGN KEY (donation_id) REFERENCES public.donations(id),
  CONSTRAINT donation_receipts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.donations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  donor_id uuid,
  tenant_id uuid,
  organization_id uuid,
  donor_member_id uuid,
  campaign_id uuid,
  amount numeric CHECK (amount >= 0::numeric),
  currency character DEFAULT 'USD'::bpchar,
  status text DEFAULT 'pending'::text,
  fee_amount numeric CHECK (fee_amount >= 0::numeric),
  net_amount numeric CHECK (net_amount >= 0::numeric),
  tax_amount numeric CHECK (tax_amount >= 0::numeric),
  provider_name text,
  provider_transaction_id text,
  provider_customer_id text,
  provider_payment_method_id text,
  is_recurring boolean DEFAULT false,
  recurring_interval text,
  recurring_end_date timestamp with time zone,
  parent_donation_id uuid,
  donation_type text DEFAULT 'general'::text,
  designation text,
  is_anonymous boolean DEFAULT false,
  is_tax_deductible boolean DEFAULT false,
  dedication text,
  comments text,
  receipt_sent_at timestamp with time zone,
  receipt_number text,
  acknowledgment_sent_at timestamp with time zone,
  acknowledgment_method text,
  refunded_at timestamp with time zone,
  refund_amount numeric CHECK (refund_amount >= 0::numeric),
  refund_reason text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT donations_pkey PRIMARY KEY (id),
  CONSTRAINT donations_donor_id_fkey FOREIGN KEY (donor_id) REFERENCES public.profiles(id),
  CONSTRAINT donations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT donations_donor_member_id_fkey FOREIGN KEY (donor_member_id) REFERENCES public.organization_members(id),
  CONSTRAINT donations_parent_donation_id_fkey FOREIGN KEY (parent_donation_id) REFERENCES public.donations(id)
);
CREATE TABLE public.event_attendees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  attendee_id uuid NOT NULL,
  organization_id uuid,
  attendee_member_id uuid,
  status text NOT NULL DEFAULT 'registered'::text,
  ticket_type text,
  num_guests integer DEFAULT 0,
  checked_in_at timestamp with time zone,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_attendees_pkey PRIMARY KEY (id),
  CONSTRAINT event_attendees_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_attendees_attendee_id_fkey FOREIGN KEY (attendee_id) REFERENCES public.profiles(id),
  CONSTRAINT event_attendees_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT event_attendees_attendee_member_id_fkey FOREIGN KEY (attendee_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organizer_id uuid NOT NULL,
  tenant_id uuid,
  organization_id uuid,
  created_by_member_id uuid,
  title text NOT NULL,
  description text,
  location text,
  address jsonb,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  capacity integer CHECK (capacity >= 0),
  is_virtual boolean DEFAULT false,
  status text DEFAULT 'draft'::text,
  event_type text DEFAULT 'general'::text,
  visibility text DEFAULT 'public'::text,
  registration_required boolean DEFAULT false,
  max_registrations integer,
  price numeric DEFAULT 0,
  currency text DEFAULT 'USD'::text,
  banner_url text,
  tags ARRAY DEFAULT '{}'::text[],
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_organizer_id_fkey FOREIGN KEY (organizer_id) REFERENCES public.profiles(id),
  CONSTRAINT events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT events_created_by_member_id_fkey FOREIGN KEY (created_by_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.job_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL,
  applicant_id uuid NOT NULL,
  organization_id uuid,
  applicant_member_id uuid,
  resume_url text,
  cover_letter text,
  current_company text,
  current_title text,
  total_experience_years integer CHECK (total_experience_years >= 0),
  linkedin_url text,
  portfolio_url text,
  status text DEFAULT 'applied'::text,
  application_stage text DEFAULT 'screening'::text,
  applied_at timestamp with time zone DEFAULT now(),
  reviewed_at timestamp with time zone,
  interviewed_at timestamp with time zone,
  offered_at timestamp with time zone,
  rejected_at timestamp with time zone,
  interview_notes text,
  hiring_manager_notes text,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  github_url text,
  website_url text,
  phone_screen_at timestamp with time zone,
  hired_at timestamp with time zone,
  withdrawn_at timestamp with time zone,
  technical_skills_rating integer CHECK (technical_skills_rating >= 1 AND technical_skills_rating <= 5),
  cultural_fit_rating integer CHECK (cultural_fit_rating >= 1 AND cultural_fit_rating <= 5),
  communication_skills_rating integer CHECK (communication_skills_rating >= 1 AND communication_skills_rating <= 5),
  overall_rating integer CHECK (overall_rating >= 1 AND overall_rating <= 5),
  expected_salary jsonb,
  notice_period_days integer,
  referred_by uuid,
  referral_notes text,
  CONSTRAINT job_applications_pkey PRIMARY KEY (id),
  CONSTRAINT job_applications_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT job_applications_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES public.profiles(id),
  CONSTRAINT job_applications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT job_applications_applicant_member_id_fkey FOREIGN KEY (applicant_member_id) REFERENCES public.organization_members(id),
  CONSTRAINT job_applications_referred_by_fkey FOREIGN KEY (referred_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  poster_id uuid NOT NULL,
  tenant_id uuid,
  organization_id uuid,
  created_by_member_id uuid,
  title text NOT NULL,
  company_name text,
  location text,
  description text,
  employment_type text,
  department text,
  experience_level text,
  education_requirements ARRAY DEFAULT '{}'::text[],
  salary_range jsonb,
  benefits ARRAY DEFAULT '{}'::text[],
  tags ARRAY,
  application_url text,
  application_instructions text,
  application_deadline timestamp with time zone,
  remote_policy text,
  status text DEFAULT 'open'::text,
  visibility text DEFAULT 'public'::text,
  featured boolean DEFAULT false,
  priority integer DEFAULT 0,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_poster_id_fkey FOREIGN KEY (poster_id) REFERENCES public.profiles(id),
  CONSTRAINT jobs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT jobs_created_by_member_id_fkey FOREIGN KEY (created_by_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  organization_id uuid,
  sender_member_id uuid,
  body text,
  attachments jsonb,
  message_type text DEFAULT 'text'::text,
  reply_to_id uuid,
  is_read boolean DEFAULT false,
  is_edited boolean DEFAULT false,
  edited_at timestamp with time zone,
  is_pinned boolean DEFAULT false,
  pinned_at timestamp with time zone,
  pinned_by uuid,
  reactions jsonb DEFAULT '{}'::jsonb,
  delivered_to jsonb DEFAULT '[]'::jsonb,
  read_by jsonb DEFAULT '[]'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id),
  CONSTRAINT messages_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT messages_sender_member_id_fkey FOREIGN KEY (sender_member_id) REFERENCES public.organization_members(id),
  CONSTRAINT messages_reply_to_id_fkey FOREIGN KEY (reply_to_id) REFERENCES public.messages(id),
  CONSTRAINT messages_pinned_by_fkey FOREIGN KEY (pinned_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.network_connections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_a uuid NOT NULL,
  user_b uuid NOT NULL,
  requester_id uuid NOT NULL,
  receiver_id uuid NOT NULL,
  organization_id uuid,
  requester_member_id uuid,
  receiver_member_id uuid,
  status text DEFAULT 'pending'::text,
  connection_note text,
  connection_type text DEFAULT 'general'::text,
  relationship_strength integer CHECK (relationship_strength >= 1 AND relationship_strength <= 5),
  shared_interests ARRAY DEFAULT '{}'::text[],
  shared_groups ARRAY DEFAULT '{}'::text[],
  accepted_at timestamp with time zone,
  rejected_at timestamp with time zone,
  blocked_at timestamp with time zone,
  withdrawn_at timestamp with time zone,
  last_interaction_at timestamp with time zone,
  visibility_settings jsonb DEFAULT '{"profile_visible": true, "contact_info_visible": true, "mutual_connections_visible": true}'::jsonb,
  recommended_by uuid,
  recommendation_strength integer CHECK (recommendation_strength >= 1 AND recommendation_strength <= 5),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT network_connections_pkey PRIMARY KEY (id),
  CONSTRAINT network_connections_user_a_fkey FOREIGN KEY (user_a) REFERENCES public.profiles(id),
  CONSTRAINT network_connections_user_b_fkey FOREIGN KEY (user_b) REFERENCES public.profiles(id),
  CONSTRAINT network_connections_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES public.profiles(id),
  CONSTRAINT network_connections_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES public.profiles(id),
  CONSTRAINT network_connections_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT network_connections_requester_member_id_fkey FOREIGN KEY (requester_member_id) REFERENCES public.organization_members(id),
  CONSTRAINT network_connections_receiver_member_id_fkey FOREIGN KEY (receiver_member_id) REFERENCES public.organization_members(id),
  CONSTRAINT network_connections_recommended_by_fkey FOREIGN KEY (recommended_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.notification_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid,
  user_member_id uuid,
  preferences jsonb DEFAULT '{"sms": false, "push": true, "email": true, "in_app": true}'::jsonb,
  category_preferences jsonb DEFAULT '{"alert": {"push": true, "email": true, "in_app": true}, "social": {"push": true, "email": true, "in_app": true}, "system": {"push": true, "email": false, "in_app": true}, "reminder": {"push": true, "email": true, "in_app": true}, "marketing": {"push": false, "email": false, "in_app": true}}'::jsonb,
  type_preferences jsonb DEFAULT '{"message": {"push": true, "email": true, "in_app": true}, "event_invite": {"push": true, "email": true, "in_app": true}, "job_application": {"push": false, "email": true, "in_app": true}, "story_published": {"push": false, "email": false, "in_app": true}, "donation_receipt": {"push": false, "email": true, "in_app": true}, "connection_request": {"push": true, "email": true, "in_app": true}}'::jsonb,
  quiet_hours_start time without time zone DEFAULT '22:00:00'::time without time zone,
  quiet_hours_end time without time zone DEFAULT '08:00:00'::time without time zone,
  timezone text DEFAULT 'UTC'::text,
  do_not_disturb boolean DEFAULT false,
  digest_frequency text DEFAULT 'daily'::text,
  last_digest_sent_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT notification_preferences_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT notification_preferences_user_member_id_fkey FOREIGN KEY (user_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.notification_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  created_by_member_id uuid,
  name text NOT NULL,
  description text,
  type text NOT NULL,
  category text DEFAULT 'general'::text,
  subject_template text,
  title_template text NOT NULL,
  body_template text NOT NULL,
  action_url_template text,
  action_label_template text,
  default_priority text DEFAULT 'medium'::text,
  default_delivery_methods ARRAY DEFAULT '{in_app}'::text[],
  is_active boolean DEFAULT true,
  language_code text DEFAULT 'en'::text,
  supported_locales ARRAY DEFAULT '{en}'::text[],
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_templates_pkey PRIMARY KEY (id),
  CONSTRAINT notification_templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT notification_templates_created_by_member_id_fkey FOREIGN KEY (created_by_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient_id uuid NOT NULL,
  organization_id uuid,
  recipient_member_id uuid,
  type text NOT NULL,
  category text DEFAULT 'general'::text,
  title text NOT NULL,
  body text,
  action_url text,
  action_label text,
  image_url text,
  priority text DEFAULT 'medium'::text,
  group_key text,
  thread_id uuid,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  is_seen boolean DEFAULT false,
  seen_at timestamp with time zone,
  delivered boolean DEFAULT false,
  delivered_at timestamp with time zone,
  delivery_methods ARRAY DEFAULT '{in_app}'::text[],
  email_sent boolean DEFAULT false,
  email_sent_at timestamp with time zone,
  push_sent boolean DEFAULT false,
  push_sent_at timestamp with time zone,
  sms_sent boolean DEFAULT false,
  sms_sent_at timestamp with time zone,
  expires_at timestamp with time zone,
  scheduled_for timestamp with time zone,
  sent_at timestamp with time zone,
  source_type text,
  source_id uuid,
  source_member_id uuid,
  clicked_at timestamp with time zone,
  dismissed_at timestamp with time zone,
  archived_at timestamp with time zone,
  payload jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.profiles(id),
  CONSTRAINT notifications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT notifications_recipient_member_id_fkey FOREIGN KEY (recipient_member_id) REFERENCES public.organization_members(id),
  CONSTRAINT notifications_source_member_id_fkey FOREIGN KEY (source_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.organization_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  invited_by_member_id uuid NOT NULL,
  target_role_id uuid NOT NULL,
  email USER-DEFINED NOT NULL,
  token text NOT NULL UNIQUE,
  status text DEFAULT 'pending'::text,
  custom_message text,
  expires_at timestamp with time zone NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT organization_invitations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_invitations_invited_by_member_id_fkey FOREIGN KEY (invited_by_member_id) REFERENCES public.organization_members(id),
  CONSTRAINT organization_invitations_target_role_id_fkey FOREIGN KEY (target_role_id) REFERENCES public.organization_roles(id)
);
CREATE TABLE public.organization_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role_id uuid NOT NULL,
  invited_by uuid,
  reports_to uuid,
  title text,
  department text,
  start_date date,
  end_date date,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  membership_status text DEFAULT 'active'::text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_members_pkey PRIMARY KEY (id),
  CONSTRAINT organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_members_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.organization_roles(id),
  CONSTRAINT organization_members_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.organization_members(id),
  CONSTRAINT organization_members_reports_to_fkey FOREIGN KEY (reports_to) REFERENCES public.organization_members(id),
  CONSTRAINT organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.organization_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  display_name text NOT NULL,
  hierarchy_level integer NOT NULL DEFAULT 0,
  permissions jsonb NOT NULL DEFAULT '{}'::jsonb,
  can_invite_roles ARRAY DEFAULT '{}'::text[],
  max_invites_per_month integer,
  is_system_role boolean DEFAULT false,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_roles_pkey PRIMARY KEY (id),
  CONSTRAINT organization_roles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organization_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL UNIQUE,
  settings jsonb DEFAULT '{"theme": "default", "features": {"events": true, "donations": true, "job_postings": true, "alumni_network": true}, "max_members": null, "allowed_domains": [], "require_approval": false, "allow_member_invites": true}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_settings_pkey PRIMARY KEY (id),
  CONSTRAINT organization_settings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organization_user_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  user_member_id uuid,
  preferences jsonb DEFAULT '{"visibility": {"show_activity": true, "show_connections": true, "show_contact_info": true, "show_in_directory": true}, "permissions": {"allow_contact": true, "allow_invites": true, "show_presence": true, "allow_mentions": true}, "communication": {"team_meetings": true, "project_updates": true, "feedback_requests": true, "department_channel": true}, "notifications": {"org_jobs": true, "org_events": true, "org_stories": true, "org_announcements": true, "department_updates": true}}'::jsonb,
  role_settings jsonb DEFAULT '{}'::jsonb,
  department_preferences jsonb DEFAULT '{}'::jsonb,
  feature_preferences jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_user_settings_pkey PRIMARY KEY (id),
  CONSTRAINT organization_user_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT organization_user_settings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_user_settings_user_member_id_fkey FOREIGN KEY (user_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug USER-DEFINED NOT NULL UNIQUE,
  website text,
  logo_url text,
  address jsonb,
  contact_email USER-DEFINED,
  phone_number text,
  description text,
  organization_type text NOT NULL DEFAULT 'educational'::text,
  employee_count_range text,
  metadata jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auth_user_id uuid NOT NULL UNIQUE,
  email USER-DEFINED NOT NULL UNIQUE,
  full_name text,
  headline text,
  avatar_url text,
  bio text,
  location text,
  graduation_year smallint CHECK (graduation_year >= 1900 AND graduation_year <= 2100),
  skills jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  tenant_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  primary_organization_id uuid,
  user_type text DEFAULT 'alumni'::text,
  degree text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_primary_organization_id_fkey FOREIGN KEY (primary_organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.stories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  author_id uuid NOT NULL,
  organization_id uuid,
  author_member_id uuid,
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  summary text,
  content text,
  excerpt text,
  featured_image_url text,
  image_gallery jsonb DEFAULT '[]'::jsonb,
  video_url text,
  category text DEFAULT 'general'::text,
  subcategory text,
  tags ARRAY,
  status text DEFAULT 'draft'::text,
  visibility text DEFAULT 'public'::text,
  featured boolean DEFAULT false,
  pinned boolean DEFAULT false,
  published_at timestamp with time zone,
  scheduled_publish_at timestamp with time zone,
  unpublished_at timestamp with time zone,
  expiration_at timestamp with time zone,
  reading_time_minutes integer CHECK (reading_time_minutes >= 0),
  word_count integer CHECK (word_count >= 0),
  view_count integer DEFAULT 0 CHECK (view_count >= 0),
  like_count integer DEFAULT 0 CHECK (like_count >= 0),
  share_count integer DEFAULT 0 CHECK (share_count >= 0),
  comment_count integer DEFAULT 0 CHECK (comment_count >= 0),
  seo_title text,
  seo_description text,
  social_media_image_url text,
  canonical_url text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stories_pkey PRIMARY KEY (id),
  CONSTRAINT stories_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(id),
  CONSTRAINT stories_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT stories_author_member_id_fkey FOREIGN KEY (author_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.story_collaborators (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  story_id uuid NOT NULL,
  collaborator_id uuid NOT NULL,
  organization_id uuid,
  collaborator_member_id uuid,
  role text NOT NULL,
  contribution_percentage integer CHECK (contribution_percentage >= 0 AND contribution_percentage <= 100),
  contribution_description text,
  is_credited boolean DEFAULT true,
  display_order integer DEFAULT 0,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT story_collaborators_pkey PRIMARY KEY (id),
  CONSTRAINT story_collaborators_story_id_fkey FOREIGN KEY (story_id) REFERENCES public.stories(id),
  CONSTRAINT story_collaborators_collaborator_id_fkey FOREIGN KEY (collaborator_id) REFERENCES public.profiles(id),
  CONSTRAINT story_collaborators_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT story_collaborators_collaborator_member_id_fkey FOREIGN KEY (collaborator_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.story_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  story_id uuid NOT NULL,
  author_id uuid NOT NULL,
  parent_comment_id uuid,
  organization_id uuid,
  author_member_id uuid,
  content text NOT NULL,
  status text DEFAULT 'published'::text,
  is_edited boolean DEFAULT false,
  edited_at timestamp with time zone,
  like_count integer DEFAULT 0 CHECK (like_count >= 0),
  reply_count integer DEFAULT 0 CHECK (reply_count >= 0),
  flagged_count integer DEFAULT 0 CHECK (flagged_count >= 0),
  moderator_notes text,
  moderated_at timestamp with time zone,
  moderated_by uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT story_comments_pkey PRIMARY KEY (id),
  CONSTRAINT story_comments_story_id_fkey FOREIGN KEY (story_id) REFERENCES public.stories(id),
  CONSTRAINT story_comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(id),
  CONSTRAINT story_comments_parent_comment_id_fkey FOREIGN KEY (parent_comment_id) REFERENCES public.story_comments(id),
  CONSTRAINT story_comments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT story_comments_author_member_id_fkey FOREIGN KEY (author_member_id) REFERENCES public.organization_members(id),
  CONSTRAINT story_comments_moderated_by_fkey FOREIGN KEY (moderated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.story_likes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  story_id uuid NOT NULL,
  user_id uuid NOT NULL,
  organization_id uuid,
  user_member_id uuid,
  reaction_type text DEFAULT 'like'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT story_likes_pkey PRIMARY KEY (id),
  CONSTRAINT story_likes_story_id_fkey FOREIGN KEY (story_id) REFERENCES public.stories(id),
  CONSTRAINT story_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT story_likes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT story_likes_user_member_id_fkey FOREIGN KEY (user_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.user_data_exports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid,
  user_member_id uuid,
  export_type text NOT NULL,
  format text DEFAULT 'json'::text,
  status text DEFAULT 'pending'::text,
  file_url text,
  file_size_bytes bigint,
  checksum text,
  requested_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '30 days'::interval),
  data_scope jsonb DEFAULT '{"include_profile": true, "include_activity": true, "include_messages": true, "include_connections": true, "include_preferences": true}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_data_exports_pkey PRIMARY KEY (id),
  CONSTRAINT user_data_exports_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_data_exports_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT user_data_exports_user_member_id_fkey FOREIGN KEY (user_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid,
  user_member_id uuid,
  session_token text NOT NULL UNIQUE,
  device_info jsonb DEFAULT '{}'::jsonb,
  ip_address inet,
  user_agent text,
  session_preferences jsonb DEFAULT '{"items_per_page": 20, "preferred_view": "grid", "filter_settings": {}, "sort_preference": "recent", "last_visited_path": "/"}'::jsonb,
  last_activity_at timestamp with time zone DEFAULT now(),
  login_at timestamp with time zone DEFAULT now(),
  logout_at timestamp with time zone,
  is_active boolean DEFAULT true,
  expires_at timestamp with time zone NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_sessions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT user_sessions_user_member_id_fkey FOREIGN KEY (user_member_id) REFERENCES public.organization_members(id)
);
CREATE TABLE public.user_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  organization_id uuid,
  user_member_id uuid,
  preferences jsonb DEFAULT '{"privacy": {"email_visibility": "organization_only", "search_visibility": true, "profile_visibility": "public", "activity_visibility": "public", "connections_visibility": "mutual"}, "security": {"login_alerts": true, "session_timeout": 60, "two_factor_auth": false, "password_requirements": "strong"}, "appearance": {"theme": "system", "language": "en", "timezone": "UTC", "date_format": "MM/DD/YYYY", "time_format": "12h"}, "communication": {"email_frequency": "immediate", "marketing_emails": false, "sms_notifications": false, "push_notifications": true, "newsletter_subscription": true}, "notifications": {"messages": true, "job_alerts": true, "event_invites": true, "story_updates": false, "donation_receipts": true, "connection_requests": true}}'::jsonb,
  organization_preferences jsonb DEFAULT '{}'::jsonb,
  profile_customization jsonb DEFAULT '{"accent_color": "#8B5CF6", "banner_color": "#3B82F6", "font_preference": "system", "layout_preference": "standard"}'::jsonb,
  data_privacy jsonb DEFAULT '{"data_sharing": "limited", "cookie_consent": true, "analytics_consent": true, "data_export_enabled": true, "account_deletion_requested": false}'::jsonb,
  accessibility jsonb DEFAULT '{"large_text": false, "high_contrast": false, "screen_reader": false, "reduced_motion": false, "keyboard_navigation": true}'::jsonb,
  experimental_features jsonb DEFAULT '{"beta_program": false, "ai_suggestions": true, "new_ui_components": true, "advanced_analytics": false}'::jsonb,
  last_accessed_at timestamp with time zone DEFAULT now(),
  settings_version integer DEFAULT 1,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_settings_pkey PRIMARY KEY (id),
  CONSTRAINT user_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_settings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT user_settings_user_member_id_fkey FOREIGN KEY (user_member_id) REFERENCES public.organization_members(id)
);